export const words = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum pretium neque, et ultrices tortor elementum vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris porttitor posuere elit feugiat blandit. Suspendisse ultrices tristique laoreet. Curabitur blandit sem lectus, ut convallis urna auctor a. Sed id placerat urna. Integer ultricies magna in diam euismod, a mattis urna congue",
    "Fusce fermentum scelerisque maximus. Mauris feugiat est ac odio accumsan, at rutrum libero elementum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget porttitor ante, nec eleifend sapien. Nulla dictum leo eu leo volutpat, non molestie ex vulputate. Nulla eleifend sodales nulla vitae bibendum. Ut placerat elit vitae sem facilisis, nec tristique neque cursus. Phasellus enim metus, ultricies id elit sit amet, tristique volutpat libero. Quisque hendrerit lobortis orci id imperdiet",
    "Phasellus et feugiat mi. Nullam porttitor nunc non ipsum bibendum porta. Quisque sit amet dolor eu libero ullamcorper tincidunt. Nullam pretium eget sem eget eleifend. Nulla facilisi. Mauris fringilla nunc ut tristique accumsan. Fusce eleifend, metus at pellentesque pharetra, purus neque convallis metus, in faucibus ligula purus id dui. Maecenas efficitur elementum velit. Fusce commodo efficitur luctus. Praesent malesuada auctor justo, vitae pulvinar lectus ornare ut. Ut placerat tempus vulputate.",
    "Curabitur mattis leo risus, eu facilisis ante semper sed. Etiam eget odio sed risus laoreet viverra facilisis vel leo. Integer sed commodo velit. Ut a condimentum erat. Mauris nisi ligula, tincidunt non lobortis ut, vestibulum sit amet neque. Cras fringilla dolor nisl. Vestibulum erat ante, commodo in est ac, elementum aliquam arcu",
    "Fusce viverra elit eu quam venenatis, eu gravida risus bibendum. Sed molestie non velit sit amet placerat. Etiam vulputate lobortis justo, eu condimentum ipsum. Curabitur iaculis convallis ipsum. Morbi congue vel ligula nec mollis. Quisque eu vehicula turpis. Etiam vehicula fringilla est in faucibus. Nam vel augue blandit, finibus enim quis, porta risus. Aenean congue accumsan neque vel rutrum. Integer vitae turpis semper, rutrum mauris accumsan, maximus odio.",
    "Vivamus sed dui id neque tempus rutrum. Ut nec libero scelerisque, egestas augue pharetra, ornare lectus. In interdum sem eu pellentesque blandit. Aenean rhoncus bibendum nulla, sed rutrum risus sagittis non. Quisque in quam facilisis massa scelerisque luctus. Donec sed bibendum nibh. Suspendisse vulputate felis ut sem malesuada, et varius magna hendrerit. In luctus, quam at pulvinar scelerisque, felis nisl tincidunt diam, vel pulvinar nulla odio eget risus.",
    "Nam eu lobortis ipsum. Sed interdum mattis hendrerit. Aliquam vehicula dolor nec mauris pulvinar viverra. Duis porttitor enim mauris, ut lacinia diam congue fermentum. Quisque iaculis maximus massa vel commodo. Pellentesque nec ligula diam. In hac habitasse platea dictumst. Curabitur odio urna, consequat id venenatis commodo, sodales a eros",
    "Phasellus non risus vitae neque pellentesque dapibus nec in ante. Donec lobortis vel erat id mollis. Morbi eu posuere est, eget gravida purus. Sed fermentum luctus sollicitudin. Mauris dolor nibh, posuere mattis eros vitae, luctus efficitur urna. Duis accumsan congue dolor, nec efficitur risus gravida egestas. Nam eu sollicitudin sem. Integer cursus faucibus nulla posuere pulvinar. Nunc felis enim."
  ];